project_id = "vopotefpdlrzfyycimqk"

[functions.generate-content]
verify_jwt = false

[functions.generate-recurring-content]
verify_jwt = false

[functions.generate-content-suggestions]
verify_jwt = false

[functions.suggest-hashtags]
verify_jwt = false

[functions.copilot-chat]
verify_jwt = false

[functions.suggest-library-content]
verify_jwt = false

[functions.transcribe-media]
verify_jwt = false

[functions.generate-video-thumbnail]
verify_jwt = false

[functions.suggest-tags]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.find-similar-content]
verify_jwt = false

[functions.process-recurring-scrapes]
verify_jwt = false